// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko <oleh@darwinscat.com> & Alisa <alisa@darwinscat.com>. Part of OrbitCab — see LICENSE.

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "Parameters.h"   // the APVTS layout (one source of truth, FROZEN IDs)
#include "IRLibrary.h"    // bundled-IR enumeration (shared with the editor)
#include "BinaryData.h"   // generated by juce_add_binary_data (the embedded IR)
#include <juce_audio_formats/juce_audio_formats.h>   // WAV decode for IR auto-level

namespace
{
    // Max IR length we load/convolve/embed. Cabinet IRs are <1 s, reverb IRs a few s;
    // this caps both the real-time convolution cost and the embedded size, and is the
    // "don't load big files" guard — longer files are truncated on load.
    constexpr double kMaxIRSeconds = 20.0;

    // Hard ceiling on a single embedded-IR blob when loading a session/preset — a legit
    // 20 s IR is a few MB, so this just stops a crafted/corrupt file from OOM-ing the host.
    constexpr size_t kMaxEmbeddedIRBytes = 64u * 1024u * 1024u;   // 64 MB / entry

    // Encode a (capped) IR buffer to a 24-bit WAV blob for self-contained sessions.
    bool encodeBufferToWav (const juce::AudioBuffer<float>& buf, double sr, juce::MemoryBlock& out)
    {
        if (buf.getNumSamples() <= 0)
            return false;
        juce::WavAudioFormat wav;
        std::unique_ptr<juce::OutputStream> os = std::make_unique<juce::MemoryOutputStream> (out, false);
        if (auto writer = wav.createWriterFor (os, juce::AudioFormatWriter::Options{}
                                                       .withSampleRate (sr > 0.0 ? sr : 48000.0)
                                                       .withNumChannels (juce::jmax (1, buf.getNumChannels()))
                                                       .withBitsPerSample (24)))
            return writer->writeFromAudioSampleBuffer (buf, 0, buf.getNumSamples());
        return false;
    }
}

//==============================================================================
OrbitCabAudioProcessor::OrbitCabAudioProcessor()
    : AudioProcessor (BusesProperties()
                          .withInput  ("Input",  juce::AudioChannelSet::stereo(), true)
                          .withOutput ("Output", juce::AudioChannelSet::stereo(), true)),
      apvts (*this, nullptr, "PARAMS", orbitcab::createParameterLayout()),
      updateCheckerInstance (JucePlugin_VersionString, appPreferencesInstance)
{
    formatManager.registerBasicFormats();   // WAV/AIFF/FLAC… for IR decode (bundled + user files)

    // Stamp the saved state with a version from day one (CLAUDE.md non-negotiable);
    // the migration logic that reads it back comes later.
    apvts.state.setProperty ("stateVersion", 1, nullptr);

    // HEAD trim default: on. A global, on-by-default session setting kept as a state-tree
    // property (not a host param) so it rides save/load + snapshots + undo. See setHeadTrim.
    apvts.state.setProperty ("headTrim", true, nullptr);

    inputGainParam = apvts.getRawParameterValue ("inputGain");
    bypassParam    = apvts.getRawParameterValue ("bypass");
    mixABParam     = apvts.getRawParameterValue ("mixAB");
    gainParam      = apvts.getRawParameterValue ("gain");
    autoLevelParam = apvts.getRawParameterValue ("autoLevel");
    for (int i = 0; i < 2; ++i)
    {
        const juce::String s = (i == 0 ? "A" : "B");
        hpfOnP[i]   = apvts.getRawParameterValue ("hpfOn"   + s);
        hpfFreqP[i] = apvts.getRawParameterValue ("hpfFreq" + s);
        lpfOnP[i]   = apvts.getRawParameterValue ("lpfOn"   + s);
        lpfFreqP[i] = apvts.getRawParameterValue ("lpfFreq" + s);
        phaseP[i]   = apvts.getRawParameterValue ("phase"   + s);
        mixP[i]     = apvts.getRawParameterValue ("mix"     + s);
        trimOnP[i]  = apvts.getRawParameterValue ("trimOn"  + s);
        muteP[i]    = apvts.getRawParameterValue ("mute"    + s);
    }

    // Re-trim when TRIM-enable toggles (deferred to the message thread — it changes the
    // loaded IR, and the toggle can arrive on the audio thread). HEAD trim isn't a param;
    // setHeadTrim flags the reload directly (message thread → no listener needed).
    apvts.addParameterListener ("trimOnA", this);
    apvts.addParameterListener ("trimOnB", this);

    // Preset-centric first start: the live state IS a preset, and that preset is the factory
    // "Default" (bundled IR #16 + HPF) — not an ad-hoc bootstrap. Establishing it here (decode
    // + store the original IR) mirrors the supported setStateInformation-before-prepareToPlay
    // path; prepareToPlay re-applies it onto the prepared engine. A host that restores a
    // session right after construction simply overwrites this in setStateInformation.
    applyFactoryDefault();

    // Poll the reload flags on the message thread. The processor is constructed (and
    // destroyed) on the message thread, so start/stop the Timer here + in the destructor —
    // never from the audio or prepare/release path, whose thread is host-defined.
    startTimerHz (30);
}

OrbitCabAudioProcessor::~OrbitCabAudioProcessor()
{
    stopTimer();   // no poll callback may run while *this is being torn down
    apvts.removeParameterListener ("trimOnA", this);
    apvts.removeParameterListener ("trimOnB", this);
}

void OrbitCabAudioProcessor::parameterChanged (const juce::String& id, float)
{
    // This can run on the audio thread (host automation of the toggle), so do the absolute
    // minimum: flag the slot dirty. The 30 Hz timer below does the heavy rebuild off the
    // audio thread. An atomic store is the only hard-RT-safe primitive used on this path.
    if      (id == "trimOnA") pendingTrimReloadA.store (true, std::memory_order_relaxed);
    else if (id == "trimOnB") pendingTrimReloadB.store (true, std::memory_order_relaxed);
}

void OrbitCabAudioProcessor::timerCallback()
{
    // Message thread. Coalesces rapid toggles/drags (many flag stores between ticks → one
    // reload). Gated on enginePrepared so a flag set before prepareToPlay / after
    // releaseResources never rebuilds onto an engine with no convolvers.
    if (! enginePrepared.load (std::memory_order_acquire))
        return;
    if (pendingTrimReloadA.exchange (false)) applyTrimAndLoad (true);
    if (pendingTrimReloadB.exchange (false)) applyTrimAndLoad (false);
}

//==============================================================================
void OrbitCabAudioProcessor::prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock)
{
    currentSampleRate = sampleRate;

    // Hand the stream to the headless core: it allocates filters/convolvers/scratch and
    // seeds its smoothers from the current parameter values (so a restored session
    // doesn't ramp from zero). The one place allocation is allowed — not the audio thread.
    engine.prepare (sampleRate, maximumExpectedSamplesPerBlock, getTotalNumOutputChannels(), packParams());

    // Re-apply the current IRs to the freshly-prepared convolvers (engine.prepare reset the
    // slots' reload-coalescing). setStateInformation may run before OR after
    // prepareToPlay, so only load the bundled default when no IR has been set yet; otherwise
    // re-apply what's already there (a restored session) instead of clobbering it.
    if (! engine.slotHasOriginal (0))
        loadBundledIR();
    else
        applyTrimAndLoad (true);
    if (slotBLoaded.load() && engine.slotHasOriginal (1))
        applyTrimAndLoad (false);

    // Seed the auto-leveler from the loaded IR's energy so the makeup starts ~converged —
    // removes most of the startup kick at the root (#48); the soft-start below is now just
    // a short safety net for the convolver warm-up residue.
    engine.seedAutoLevel();

    enginePrepared.store (true, std::memory_order_release);   // arm the reload poll timer

    // One-shot startup fade (#48): a short ramp from silence on the first non-silent block,
    // covering the convolver warm-up the auto-level seed can't (the IR loads async). With the
    // seed doing the heavy lifting this is now ~imperceptible (was 150 ms before the seed).
    softStartArmed = true;
    softStart      = 1.0f;
    softStartStep  = (float) (1.0 / (0.03 * sampleRate));     // 30 ms
}

bool OrbitCabAudioProcessor::loadIRFromReader (std::unique_ptr<juce::AudioFormatReader> reader, bool slotA)
{
    // Shared IR-load path (bundled + user files, either slot). Decode the whole IR and
    // hand it to the slot's core cab::IRSlot, which keeps it so TRIM can re-truncate
    // without re-decoding. A fresh IR starts untrimmed. Loaded AS-IS (Normalise::no): the
    // live wet->dry match does the leveling. Stereo::yes => mono IR applied to L+R.
    if (reader == nullptr || reader->lengthInSamples <= 0)
        return false;                                 // unreadable / empty — caller leaves the slot untouched

    const double srLoaded = reader->sampleRate > 0.0 ? reader->sampleRate : currentSampleRate;

    // Cap the load (the "don't load big files" guard): only the first kMaxIRSeconds are
    // decoded, so a long file can't blow up the convolution or the embedded size.
    const juce::int64 maxSamples = (juce::int64) (kMaxIRSeconds * srLoaded);
    const int n = (int) juce::jmin (reader->lengthInSamples, maxSamples);

    juce::AudioBuffer<float> decoded ((int) reader->numChannels, n);
    reader->read (&decoded, 0, n, 0, true, true);

    // The IRSlot stores the original + detects leading silence (HEAD trim) on its own.
    engine.setSlotOriginalIR (slotA ? 0 : 1, decoded.getArrayOfReadPointers(),
                              decoded.getNumChannels(), n, srLoaded);
    (slotA ? trimFractionA : trimFractionB) = 1.0f;             // new IR => full length
    (slotA ? slotNameA : slotNameB).clear();                   // display name derives from the ref/file unless restore overrides it
    if (! slotA)
        slotBLoaded.store (true, std::memory_order_relaxed);

    applyTrimAndLoad (slotA);
    return true;
}

void OrbitCabAudioProcessor::setTrim (float fraction01, bool slotA)
{
    // Store the latest fraction + flag the slot dirty; the 30 Hz poll timer coalesces rapid
    // drags into one reload (calling the loader on every micro-move floods it so the final
    // position never lands). Called from the editor's waveform drag — message thread.
    (slotA ? trimFractionA : trimFractionB) = juce::jlimit (0.0f, 1.0f, fraction01);
    (slotA ? pendingTrimReloadA : pendingTrimReloadB).store (true, std::memory_order_relaxed);
}

void OrbitCabAudioProcessor::applyTrimAndLoad (bool slotA)
{
    // Rebuild + atomic-swap the (head-trimmed, then trimmed, faded) IR in the slot's core
    // cab::IRSlot, off the audio thread. TRIM/HEAD enables come from the params; the
    // drag fraction is the persisted position. Then refresh the host tail = longest slot.
    const int slotIdx = slotA ? 0 : 1;
    const bool trimOn = trimOnP[slotIdx] != nullptr && trimOnP[slotIdx]->load() > 0.5f;
    const bool headOn = getHeadTrim();                 // global, on-by-default session setting
    const float frac  = slotA ? trimFractionA : trimFractionB;

    engine.slotApplyTrim (slotIdx, trimOn, frac, headOn);

    const double aSec = engine.slotTrimmedSeconds (0);
    const double bSec = slotBLoaded.load() ? engine.slotTrimmedSeconds (1) : 0.0;
    irLengthSeconds = juce::jmax (0.01, juce::jmax (aSec, bSec));
}

void OrbitCabAudioProcessor::setHeadTrim (bool on)
{
    // Message thread (gear settings toggle). Persist the flag on the state tree, then flag
    // BOTH slots for rebuild — the 30 Hz reload poll re-trims them off the audio thread
    // (same path as TRIM/IR-swap), gated by enginePrepared. RT rule: no reload happens here.
    apvts.state.setProperty ("headTrim", on, nullptr);
    pendingTrimReloadA.store (true, std::memory_order_relaxed);
    pendingTrimReloadB.store (true, std::memory_order_relaxed);
}

void OrbitCabAudioProcessor::loadBundledIR()
{
    if (auto* r = formatManager.createReaderFor (std::make_unique<juce::MemoryInputStream> (
            BinaryData::_01cookiemonster_wav, (size_t) BinaryData::_01cookiemonster_wavSize, false)))
    {
        if (loadIRFromReader (std::unique_ptr<juce::AudioFormatReader> (r), true))
        {
            slotRefA = "01-cookie-monster.wav";
            slotBundledA = true;
            return;
        }
    }

    // Fallback: byte-array load with JUCE's own normalisation (via the slot's convolver).
    // No decoded original here (so TRIM is a no-op), but keep the slot ref consistent.
    engine.slotLoadBytesFallback (0, BinaryData::_01cookiemonster_wav, (size_t) BinaryData::_01cookiemonster_wavSize);
    slotRefA = "01-cookie-monster.wav";
    slotBundledA = true;
}

void OrbitCabAudioProcessor::loadIRFromFile (const juce::File& file, bool slotA)
{
    std::unique_ptr<juce::AudioFormatReader> reader (formatManager.createReaderFor (file));
    if (reader == nullptr)
        return;                                       // unreadable / missing → leave the slot as-is
    if (! loadIRFromReader (std::move (reader), slotA))
        return;                                       // decode failed → leave the slot as-is
    const auto path = file.getFullPathName();
    (slotA ? slotRefA : slotRefB) = path;
    (slotA ? slotBundledA : slotBundledB) = false;
    cacheEmbeddedIR (path, slotA);                    // keep bytes for a self-contained session
}

void OrbitCabAudioProcessor::cacheEmbeddedIR (const juce::String& path, bool slotA)
{
    // Encode the just-loaded (capped) IR — the slot's original buffer in the core — to a
    // WAV blob so it can be embedded in the saved state and recalled even if the file moves.
    const int slotIdx = slotA ? 0 : 1;
    juce::MemoryBlock mb;
    if (encodeBufferToWav (engine.slotOriginal (slotIdx), engine.slotOriginalSampleRate (slotIdx), mb))
        embeddedIRs[path] = std::move (mb);
}

void OrbitCabAudioProcessor::loadIRRef (const juce::String& ref, bool bundled, bool slotA)
{
    if (ref.isEmpty())
        return;
    if (bundled)
    {
        loadBundledByName (ref, slotA);
        return;
    }
    // Prefer this session's embedded bytes (survives a moved file / another machine).
    if (auto it = embeddedIRs.find (ref); it != embeddedIRs.end() && it->second.getSize() > 0)
    {
        if (loadIRFromReader (std::unique_ptr<juce::AudioFormatReader> (formatManager.createReaderFor (
            std::make_unique<juce::MemoryInputStream> (it->second.getData(), it->second.getSize(), false))), slotA))
        {
            (slotA ? slotRefA : slotRefB) = ref;
            (slotA ? slotBundledA : slotBundledB) = false;
            return;
        }
    }
    loadIRFromFile (juce::File (ref), slotA);          // embedded missing/corrupt → fall back to disk
}

void OrbitCabAudioProcessor::addUserIR (const juce::File& file)
{
    const auto path = file.getFullPathName();
    if (path.isEmpty())
        return;
    userIRPaths.removeString (path);                 // dedup → move to front (most recent)
    userIRPaths.insert (0, path);
    while (userIRPaths.size() > kMaxUserIRs)
        userIRPaths.remove (userIRPaths.size() - 1);
}

void OrbitCabAudioProcessor::loadIRFromMemory (const void* data, size_t sizeInBytes, bool slotA,
                                           const juce::String& bundledName)
{
    // Bundled IR: wrap the embedded bytes in a stream and reuse the shared path.
    // `false` => the stream does not own/copy the data (it's a static BinaryData blob).
    if (! loadIRFromReader (std::unique_ptr<juce::AudioFormatReader> (formatManager.createReaderFor (
        std::make_unique<juce::MemoryInputStream> (data, sizeInBytes, false))), slotA))
        return;                                       // bad bytes → don't claim the slot loaded
    (slotA ? slotRefA : slotRefB) = bundledName;
    (slotA ? slotBundledA : slotBundledB) = true;
}

void OrbitCabAudioProcessor::loadBundledByName (const juce::String& filename, bool slotA)
{
    // Find a bundled IR by its original filename and load it into the slot,
    // via the shared IRLibrary enumeration (one source of truth).
    for (const auto& b : orbitcab::bundledIRs())
        if (b.name == filename)
        {
            loadIRFromMemory (b.data, (size_t) b.size, slotA, filename);
            return;
        }
}

void OrbitCabAudioProcessor::clearSlotB()
{
    // Unload B: stop convolving it and force MIX back to A. The slot's convolver keeps its
    // last IR internally but we just stop feeding/using it (process skips B when !bLoaded).
    slotBLoaded.store (false, std::memory_order_relaxed);
    engine.clearSlotOriginal (1);
    slotRefB.clear();
    slotBundledB = false;
}

void OrbitCabAudioProcessor::restoreIRsFromTree (const juce::ValueTree& ir)
{
    // user-IR history — only when present (snapshot trees omit it, so recalling
    // a snapshot must not wipe the global history; full session state always carries it).
    if (ir.hasProperty ("userIRs"))
    {
        userIRPaths.clear();
        userIRPaths.addLines (ir.getProperty ("userIRs").toString());
        userIRPaths.removeEmptyStrings();
    }

    // Slot A — bundled name / embedded bytes / file on disk (loadIRRef picks the source).
    const juce::String aRef = ir.getProperty ("aRef").toString();
    if (aRef.isNotEmpty())
    {
        loadIRRef (aRef, (bool) ir.getProperty ("aBundled", true), true);
        slotNameA = ir.getProperty ("aName", {}).toString();   // portable-preset display name (empty in sessions)
        setTrim ((float) ir.getProperty ("aTrim", 1.0f), true);
    }

    // Slot B
    if ((bool) ir.getProperty ("bLoaded", false))
    {
        const juce::String bRef = ir.getProperty ("bRef").toString();
        if (bRef.isNotEmpty())
        {
            loadIRRef (bRef, (bool) ir.getProperty ("bBundled", true), false);
            slotNameB = ir.getProperty ("bName", {}).toString();
            setTrim ((float) ir.getProperty ("bTrim", 1.0f), false);
        }
    }
    else
    {
        clearSlotB();
    }
}

//==============================================================================
// A/B/C/D compare — snapshot registers (full settings, live-register model).
//==============================================================================
void OrbitCabAudioProcessor::writeIRRefs (juce::ValueTree& ir) const
{
    // The per-slot IR references — shared by the session tree (buildStateTree) and the
    // A/B/C/D snapshots (captureStateTree) so the two can't drift.
    ir.setProperty ("aBundled", slotBundledA,      nullptr);
    ir.setProperty ("aRef",     slotRefA,          nullptr);
    ir.setProperty ("aTrim",    trimFractionA,     nullptr);
    ir.setProperty ("bLoaded",  slotBLoaded.load(), nullptr);
    ir.setProperty ("bBundled", slotBundledB,      nullptr);
    ir.setProperty ("bRef",     slotRefB,          nullptr);
    ir.setProperty ("bTrim",    trimFractionB,     nullptr);
}

juce::ValueTree OrbitCabAudioProcessor::captureStateTree()
{
    // A snapshot of the live state: the parameter tree + the per-slot IR references.
    // No user-IR history (that's a global accumulator, not part of a "sound").
    juce::ValueTree t ("Snap");
    t.appendChild (apvts.copyState(), nullptr);

    juce::ValueTree ir ("IR");
    writeIRRefs (ir);
    t.appendChild (ir, nullptr);
    return t;
}

void OrbitCabAudioProcessor::applyStateTree (const juce::ValueTree& t)
{
    // Recall a snapshot: replace the params (a copy, so live edits don't mutate the
    // stored register) + reload the referenced IRs. replaceState keeps the existing
    // parameter objects, so cached raw-pointers + editor attachments stay valid.
    if (auto params = t.getChildWithName (apvts.state.getType()); params.isValid())
        apvts.replaceState (params.createCopy());
    if (auto ir = t.getChildWithName ("IR"); ir.isValid())
        restoreIRsFromTree (ir);
}

void OrbitCabAudioProcessor::switchToSnapshot (int index)
{
    if (index < 0 || index >= kNumSnapshots || index == activeSnapshot)
        return;
    snapshots[activeSnapshot] = captureStateTree();   // stash the live state into the active register
    if (snapshots[index].isValid())
        applyStateTree (snapshots[index]);            // recall an existing register
    // else: a fresh register inherits the current state (nothing to apply)
    activeSnapshot = index;
}

//==============================================================================
// Undo / redo — coalesced full-state snapshots.
//==============================================================================
void OrbitCabAudioProcessor::undoTick()
{
    // Driven by the editor timer. Commit one undo step once the state has settled
    // (unchanged for kUndoSettleTicks), so a slider drag becomes a single step.
    auto cur = captureStateTree();
    if (! undoBaseline.isValid())                       // first tick → seed the baseline
    {
        undoBaseline = cur;
        undoPrev     = cur;
        undoSettle   = 0;
        return;
    }
    if (! cur.isEquivalentTo (undoPrev))                // still changing → wait
    {
        undoPrev   = cur;
        undoSettle = 0;
        return;
    }
    if (! cur.isEquivalentTo (undoBaseline) && ++undoSettle >= kUndoSettleTicks)
    {
        undoStack.push_back (undoBaseline);
        if ((int) undoStack.size() > kMaxUndo)
            undoStack.erase (undoStack.begin());
        redoStack.clear();
        undoBaseline = cur;
        undoSettle   = 0;
    }
}

bool OrbitCabAudioProcessor::undo()
{
    if (undoStack.empty())
        return false;
    redoStack.push_back (captureStateTree());
    const auto target = undoStack.back();
    undoStack.pop_back();
    applyStateTree (target);
    undoBaseline = target;
    undoPrev     = target;
    undoSettle   = 0;
    return true;
}

bool OrbitCabAudioProcessor::redo()
{
    if (redoStack.empty())
        return false;
    undoStack.push_back (captureStateTree());
    const auto target = redoStack.back();
    redoStack.pop_back();
    applyStateTree (target);
    undoBaseline = target;
    undoPrev     = target;
    undoSettle   = 0;
    return true;
}

const juce::MemoryBlock* OrbitCabAudioProcessor::embeddedIRBytes (const juce::String& path) const
{
    auto it = embeddedIRs.find (path);
    return (it != embeddedIRs.end() && it->second.getSize() > 0) ? &it->second : nullptr;
}

void OrbitCabAudioProcessor::releaseResources()
{
    // Disarm the reload poll timer before tearing down DSP state, so timerCallback can't
    // rebuild onto a reset engine. Then drop the engine's transient state (filter/convolver/
    // follower); prepareToPlay re-seeds everything + re-applies the IRs before audio resumes.
    enginePrepared.store (false, std::memory_order_release);
    engine.reset();
    softStartArmed = true;          // re-arm the startup fade for the next play (#48)
    softStart      = 1.0f;
}

bool OrbitCabAudioProcessor::isBusesLayoutSupported (const BusesLayout& layouts) const
{
    // Accept matching mono->mono or stereo->stereo only; reject the rest.
    const auto& mainOut = layouts.getMainOutputChannelSet();
    const auto& mainIn  = layouts.getMainInputChannelSet();

    if (mainOut != juce::AudioChannelSet::mono()
        && mainOut != juce::AudioChannelSet::stereo())
        return false;

    return mainIn == mainOut;
}

//==============================================================================
void OrbitCabAudioProcessor::processBlock (juce::AudioBuffer<float>& buffer,
                                       juce::MidiBuffer& midiMessages)
{
    juce::ignoreUnused (midiMessages);
    juce::ScopedNoDenormals noDenormals;

    const int numCh      = getTotalNumInputChannels();
    const int numSamples = buffer.getNumSamples();

    // Clear any output channels without a matching input (avoids garbage).
    for (int ch = numCh; ch < getTotalNumOutputChannels(); ++ch)
        buffer.clear (ch, 0, numSamples);

    // The whole signal path lives in the headless core (cab::CabEngine). Pack the
    // current parameters (RT-safe atomic loads) and hand it the planar channels in
    // place; `isNonRealtime()` lets it skip the spectrum capture during a bounce.
    engine.process (buffer.getArrayOfWritePointers(), numCh, numSamples, packParams(), isNonRealtime());

    // One-shot soft-start: fade the output up from silence on the first non-silent block
    // after prepareToPlay / releaseResources, to mask the engine's auto-level + convolver
    // warm-up transient (#48). A host-side cosmetic — kept out of the pure DSP core.
    if (softStartArmed && buffer.getMagnitude (0, numSamples) > 1.0e-5f)
    {
        softStartArmed = false;
        softStart      = 0.0f;
    }
    if (softStart < 1.0f)
    {
        const int chs = buffer.getNumChannels();
        for (int n = 0; n < numSamples; ++n)
        {
            const float ss = softStart;
            for (int ch = 0; ch < chs; ++ch)
                buffer.getWritePointer (ch)[n] *= ss;
            softStart = juce::jmin (1.0f, softStart + softStartStep);
        }
    }
}

//==============================================================================
// Pack the cached APVTS atomics into a plain cab::Params for the core. RT-safe
// (only atomic loads); called from processBlock and to seed the engine in prepare.
cab::Params OrbitCabAudioProcessor::packParams() const
{
    cab::Params p;
    p.inputGainDb  = inputGainParam->load();
    p.outputGainDb = gainParam->load();
    p.mixAB01      = mixABParam->load() * 0.01f;
    p.bypass       = bypassParam->load()    > 0.5f;
    p.autoLevel    = autoLevelParam->load() > 0.5f;
    p.bLoaded      = slotBLoaded.load (std::memory_order_relaxed);
    for (int i = 0; i < 2; ++i)
    {
        p.slot[i].hpfOn    = hpfOnP[i]->load() > 0.5f;
        p.slot[i].lpfOn    = lpfOnP[i]->load() > 0.5f;
        p.slot[i].phase    = phaseP[i]->load() > 0.5f;
        p.slot[i].mute     = muteP[i]->load()  > 0.5f;
        p.slot[i].hpfHz    = hpfFreqP[i]->load();
        p.slot[i].lpfHz    = lpfFreqP[i]->load();
        p.slot[i].dryWet01 = mixP[i]->load() * 0.01f;
    }
    return p;
}

//==============================================================================
juce::AudioProcessorEditor* OrbitCabAudioProcessor::createEditor()
{
    return new OrbitCabAudioProcessorEditor (*this);
}

//==============================================================================
// Strip external-IR file paths for portable preset export: re-key the IRPool + the slot
// refs by content hash, attach a display name, and drop the recent-files list.
static void makePortable (juce::ValueTree& root)
{
    std::map<juce::String, juce::String> pathToHash;
    if (auto pool = root.getChildWithName ("IRPool"); pool.isValid())
        for (auto e : pool)
        {
            const auto wav  = e.getProperty ("wav").toString();
            const auto hash = "ir-" + juce::String::toHexString (wav.hashCode64());   // content-derived, path-free key
            pathToHash[e.getProperty ("path").toString()] = hash;
            e.setProperty ("path", hash, nullptr);
        }

    auto portIR = [&] (juce::ValueTree ir)
    {
        if (! ir.isValid()) return;
        ir.removeProperty ("userIRs", nullptr);                          // recents leak the folder tree
        for (const char* side : { "a", "b" })
        {
            if ((bool) ir.getProperty (juce::String (side) + "Bundled", true)) continue;   // bundled = no path
            const juce::String refK (juce::String (side) + "Ref");
            const auto ref = ir.getProperty (refK).toString();
            if (ref.isEmpty()) continue;
            ir.setProperty (juce::String (side) + "Name", juce::File (ref).getFileName(), nullptr);   // display name
            if (auto it = pathToHash.find (ref); it != pathToHash.end())
                ir.setProperty (refK, it->second, nullptr);              // absolute path -> content hash
        }
    };

    portIR (root.getChildWithName ("IR"));
    if (auto snaps = root.getChildWithName ("Snapshots"); snaps.isValid())
        for (auto s : snaps)
            if (auto snap = s.getChild (0); snap.isValid())              // S > Snap > IR
                portIR (snap.getChildWithName ("IR"));

    // <meta> is descriptive JSON; strip any absolute path in its irRefs[].fallback so a
    // shared preset can't reveal the sharer's folder layout (mirrors the <IR> path-strip
    // above). Round-trips through fromVar/toVar, so unknown keys are preserved.
    if (auto m = root.getChildWithName ("meta"); m.isValid())
    {
        auto meta = orbitcab::PresetMeta::fromVar (orbitcab::parseJSON (m.getProperty ("json").toString()));
        for (auto& r : meta.irRefs)
            if (! r.bundled && r.fallback.isNotEmpty())
                r.fallback = juce::File (r.fallback).getFileName();      // absolute path -> bare filename
        m.setProperty ("json", orbitcab::toJSON (meta.toVar()), nullptr);
        m.removeProperty ("baselineHash", nullptr);                     // session dirty-baseline — not shareable
        m.setProperty ("factory", false, nullptr);                     // a shared/exported preset is never the Default
    }
}

//==============================================================================
std::vector<orbitcab::IrRef> OrbitCabAudioProcessor::currentIrRefs() const
{
    // Display-layer references for the preset <meta>: which IR each slot uses, so a browser
    // can show them without decoding audio or applying state. The functional load still goes
    // through <IR> + the embedded-bytes pool. `id` (content hash) is left empty — the
    // IR-hashing / library milestone fills it; the resolve path's id branch is dormant today.
    auto baseName = [] (const juce::String& ref, bool bundled)
    {
        return bundled ? ref.upToLastOccurrenceOf (".", false, false)      // "16-nacho-guacamole"
                       : juce::File (ref).getFileNameWithoutExtension();
    };
    auto make = [&] (const juce::String& ref, bool bundled, const char* slot)
    {
        orbitcab::IrRef r;
        r.slot     = slot;
        r.bundled  = bundled;
        r.fallback = ref;
        r.name     = baseName (ref, bundled);
        return r;                                  // r.id intentionally empty (reserved)
    };

    std::vector<orbitcab::IrRef> refs;
    if (slotRefA.isNotEmpty())
        refs.push_back (make (slotRefA, slotBundledA, "A"));
    if (slotBLoaded.load() && slotRefB.isNotEmpty())
        refs.push_back (make (slotRefB, slotBundledB, "B"));
    return refs;
}

//==============================================================================
// Preset-centric model: the factory Default + dirty tracking.
//==============================================================================
void OrbitCabAudioProcessor::loadFactoryDefaultIR()
{
    // The factory Default's cabinet: bundled Emerald IR #16. By filename PREFIX (not a
    // hardcoded full name) so a later rename of the bundled tree doesn't silently fall
    // through to the cookie-monster fallback.
    for (const auto& b : orbitcab::bundledIRs())
        if (b.name.startsWith ("16"))
        {
            loadIRFromMemory (b.data, (size_t) b.size, true, b.name);
            return;
        }
    loadBundledIR();   // fallback (shouldn't happen): the original bootstrap IR
}

void OrbitCabAudioProcessor::applyFactoryDefault()
{
    // The factory starting point (preset-centric first start + the editor's "Default" item):
    // a clean single-box sound — bundled IR #16 with the HPF engaged. Reset every parameter
    // to its default first so the result is reproducible regardless of the current state,
    // then load the IR + arm the HPF + stamp the read-only "Default" identity. Message-thread.
    for (auto* p : getParameters())
        if (auto* rp = dynamic_cast<juce::RangedAudioParameter*> (p))
            rp->setValueNotifyingHost (rp->getDefaultValue());

    clearSlotB();                                   // box II empty (single IR)
    loadFactoryDefaultIR();                          // box I → IR #16
    if (auto* q = apvts.getParameter ("hpfOnA"))
        q->setValueNotifyingHost (1.0f);             // HPF on (default 80 Hz)

    currentMeta      = orbitcab::PresetMeta();
    currentMeta.name = "Default";
    presetIsFactory  = true;
    captureBaseline();                               // a fresh Default is clean (not dirty)
}

juce::String OrbitCabAudioProcessor::stateFingerprint()
{
    // A cheap, stable hash of the preset-defining state (params incl. headTrim + IR refs —
    // the same tree the snapshots/undo capture). Excludes <meta>, view-prefs, snapshots and
    // undo, so only sound-affecting edits flip it. Drives the dirty indicator.
    return juce::String (captureStateTree().toXmlString().hashCode64());
}

//==============================================================================
juce::ValueTree OrbitCabAudioProcessor::buildStateTree()
{
    // Wrap the parameter tree + per-slot IR references in one root so a saved
    // DAW session (or a preset) restores both the params and which IRs were loaded. Each
    // slot stores a *reference* (bundled filename or file path) + trim. External (user)
    // IRs additionally embed their audio in an IRPool node so the session/preset is
    // self-contained — survives a moved file / another machine. Bundled IRs are
    // never embedded (their bytes live in the plugin binary).
    juce::ValueTree root ("OrbitCabState");
    root.setProperty ("stateVersion", 3, nullptr);   // 3 = + preset <meta> (descriptive identity)

    // Preset identity (preset-centric model): the descriptive metadata + which IRs the live
    // state uses, as JSON in a <meta> child. Built into a LOCAL copy so serialising never
    // mutates the live member (some hosts call getStateInformation off the message thread),
    // and stamped with the build version + a modified timestamp. The functional load stays
    // in <IR>/<IRPool>; this is the cheap descriptive layer a browser reads on its own.
    {
        orbitcab::PresetMeta meta = currentMeta;
        meta.irRefs     = currentIrRefs();
        meta.appVersion = JucePlugin_VersionString;
        meta.modifiedAt = orbitcab::nowIso8601();
        juce::ValueTree metaTree ("meta");
        metaTree.setProperty ("json", orbitcab::toJSON (meta.toVar()), nullptr);
        // Preset-centric session bookkeeping (NOT part of the shareable JSON): the dirty
        // baseline + the factory flag, so a dirty "Default *" and "this is the read-only
        // Default" both survive a DAW session reload. makePortable strips these for export.
        metaTree.setProperty ("baselineHash", presetBaselineFingerprint, nullptr);
        metaTree.setProperty ("factory",      presetIsFactory,           nullptr);
        root.appendChild (metaTree, nullptr);
    }

    root.appendChild (apvts.copyState(), nullptr);

    juce::ValueTree ir ("IR");
    writeIRRefs (ir);
    ir.setProperty ("userIRs",  userIRPaths.joinIntoString ("\n"), nullptr);   // user-IR history
    root.appendChild (ir, nullptr);

    // A/B/C/D snapshots: the active register's true content is the live state, so capture
    // it now; the others persist as-is (invalid = never used → empty child).
    juce::ValueTree snaps ("Snapshots");
    snaps.setProperty ("active", activeSnapshot, nullptr);
    for (int i = 0; i < kNumSnapshots; ++i)
    {
        juce::ValueTree slot ("S");
        const juce::ValueTree content = (i == activeSnapshot) ? captureStateTree() : snapshots[i];
        if (content.isValid())
            slot.appendChild (content.createCopy(), nullptr);
        snaps.appendChild (slot, nullptr);
    }
    root.appendChild (snaps, nullptr);

    // IRPool: embed the audio of every external IR referenced by the live state or
    // any snapshot, once per unique path (deduped). base64 WAV; bundled refs are skipped.
    {
        juce::StringArray refs;
        auto addRef = [&] (bool bundled, const juce::String& r)
        { if (! bundled && r.isNotEmpty()) refs.addIfNotAlreadyThere (r); };

        addRef (slotBundledA, slotRefA);
        if (slotBLoaded.load()) addRef (slotBundledB, slotRefB);
        for (int i = 0; i < kNumSnapshots; ++i)
        {
            const juce::ValueTree t = (i == activeSnapshot) ? captureStateTree() : snapshots[i];
            if (auto irn = t.getChildWithName ("IR"); irn.isValid())
            {
                addRef ((bool) irn.getProperty ("aBundled", true), irn.getProperty ("aRef").toString());
                if ((bool) irn.getProperty ("bLoaded", false))
                    addRef ((bool) irn.getProperty ("bBundled", true), irn.getProperty ("bRef").toString());
            }
        }

        juce::ValueTree pool ("IRPool");
        for (const auto& r : refs)
            if (auto it = embeddedIRs.find (r); it != embeddedIRs.end() && it->second.getSize() > 0)
            {
                juce::ValueTree e ("E");
                e.setProperty ("path", r, nullptr);
                e.setProperty ("wav",  juce::Base64::toBase64 (it->second.getData(), it->second.getSize()), nullptr);
                pool.appendChild (e, nullptr);
            }
        root.appendChild (pool, nullptr);
    }

    return root;
}

//==============================================================================
void OrbitCabAudioProcessor::getStateInformation (juce::MemoryBlock& destData)
{
    if (auto xml = buildStateTree().createXml())
        copyXmlToBinary (*xml, destData);
}

void OrbitCabAudioProcessor::getStateForPreset (juce::MemoryBlock& destData)
{
    // Strip external-IR paths so a shared preset can't reveal the sharer's folder layout.
    auto root = buildStateTree();
    makePortable (root);
    if (auto xml = root.createXml())
        copyXmlToBinary (*xml, destData);
}

void OrbitCabAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    auto xml = getXmlFromBinary (data, sizeInBytes);
    if (xml == nullptr)
        return;

    auto root = juce::ValueTree::fromXml (*xml);

    if (root.hasType ("OrbitCabState"))
    {
        // Preset <meta> (v3). Absent in v2 / param-only states → reset to a clean default so
        // a stale name can't linger; the name then derives from the file (listWithMeta / editor).
        // baselineHash/factory are session bookkeeping: a session restores its dirty baseline +
        // factory flag; a portable preset (stripped) lands clean (PresetManager re-baselines it).
        if (auto m = root.getChildWithName ("meta"); m.isValid())
        {
            currentMeta = orbitcab::PresetMeta::fromVar (orbitcab::parseJSON (m.getProperty ("json").toString()));
            presetBaselineFingerprint = m.getProperty ("baselineHash", {}).toString();
            presetIsFactory = (bool) m.getProperty ("factory", false);
        }
        else
        {
            currentMeta = orbitcab::PresetMeta();
            presetBaselineFingerprint.clear();
            presetIsFactory = false;
        }

        if (auto params = root.getChildWithName (apvts.state.getType()); params.isValid())
            apvts.replaceState (params);

        // Rehydrate embedded IRs BEFORE restoring refs, so loadIRRef finds the bytes
        // (and so snapshot recall works later even if the original files aren't present).
        if (auto pool = root.getChildWithName ("IRPool"); pool.isValid())
            for (auto e : pool)
            {
                const juce::String path = e.getProperty ("path").toString();
                const juce::String b64  = e.getProperty ("wav").toString();
                if (path.isEmpty() || b64.isEmpty())
                    continue;
                if ((size_t) b64.getNumBytesAsUTF8() / 4 * 3 > kMaxEmbeddedIRBytes)
                    continue;                          // oversized blob (crafted/corrupt) → skip, don't OOM
                juce::MemoryOutputStream mos;
                if (juce::Base64::convertFromBase64 (mos, b64) && mos.getDataSize() <= kMaxEmbeddedIRBytes)
                    embeddedIRs[path] = juce::MemoryBlock (mos.getData(), mos.getDataSize());
            }

        if (auto ir = root.getChildWithName ("IR"); ir.isValid())
            restoreIRsFromTree (ir);

        // A/B/C/D snapshots (absent in pre-snapshot sessions → registers stay empty).
        if (auto snaps = root.getChildWithName ("Snapshots"); snaps.isValid())
        {
            activeSnapshot = juce::jlimit (0, kNumSnapshots - 1, (int) snaps.getProperty ("active", 0));
            for (int i = 0; i < kNumSnapshots; ++i)
                snapshots[i] = (i < snaps.getNumChildren())
                                   ? snaps.getChild (i).getChildWithName ("Snap").createCopy()
                                   : juce::ValueTree();
        }
    }
    else if (xml->hasTagName (apvts.state.getType()))
    {
        // Backward-compat: earlier sessions stored just the PARAMS tree (no <meta>).
        currentMeta = orbitcab::PresetMeta();
        presetBaselineFingerprint.clear();
        presetIsFactory = false;
        apvts.replaceState (root);
    }

    // Migration: HEAD trim was per-slot params (headOnA/B, default off) through 1.0.x; it's
    // now the global `headTrim` property (default on). A session saved before 1.1 carries no
    // such property — fall back to the OLD default (off) so opening an old project doesn't
    // silently start head-trimming the IRs. Post-1.1 sessions carry the property and keep
    // their value, so property-absence IS the version marker (no stateVersion bump needed).
    // The IR re-trim is deferred to the reload poll, which reads getHeadTrim() after this returns.
    if (! apvts.state.hasProperty ("headTrim"))
        apvts.state.setProperty ("headTrim", false, nullptr);

    // A loaded session/preset is a fresh starting point — drop undo history and re-seed
    // the baseline (lazily, on the next undoTick) so you can't undo past the load.
    undoStack.clear();
    redoStack.clear();
    undoBaseline = juce::ValueTree();
    undoPrev     = juce::ValueTree();
    undoSettle   = 0;
}

//==============================================================================
// The factory the host calls to instantiate the plugin.
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new OrbitCabAudioProcessor();
}
