// SPDX-License-Identifier: AGPL-3.0-or-later
// Copyright (c) 2026 Darwin's Cat — Oleh Tsymaienko <oleh@darwinscat.com> & Alisa <alisa@darwinscat.com>. Part of OrbitCab — see LICENSE.

#include "PluginProcessor.h"
#include "PluginEditor.h"
#include "Parameters.h"   // the APVTS layout (one source of truth, FROZEN IDs)
#include "IRLibrary.h"    // bundled-IR enumeration (shared with the editor)
#include "BinaryData.h"   // generated by juce_add_binary_data (the embedded IR)
#include <juce_audio_formats/juce_audio_formats.h>   // WAV decode for IR auto-level

namespace
{
    // Max IR length we load/convolve/embed. Cabinet IRs are <1 s, reverb IRs a few s;
    // this caps both the real-time convolution cost and the embedded size, and is the
    // "don't load big files" guard — longer files are truncated on load.
    constexpr double kMaxIRSeconds = 20.0;

    // Hard ceiling on a single embedded-IR blob when loading a session/preset — a legit
    // 20 s IR is a few MB, so this just stops a crafted/corrupt file from OOM-ing the host.
    constexpr size_t kMaxEmbeddedIRBytes = 64u * 1024u * 1024u;   // 64 MB / entry

    // Encode a (capped) IR buffer to a 24-bit WAV blob for self-contained sessions.
    bool encodeBufferToWav (const juce::AudioBuffer<float>& buf, double sr, juce::MemoryBlock& out)
    {
        if (buf.getNumSamples() <= 0)
            return false;
        juce::WavAudioFormat wav;
        std::unique_ptr<juce::OutputStream> os = std::make_unique<juce::MemoryOutputStream> (out, false);
        if (auto writer = wav.createWriterFor (os, juce::AudioFormatWriter::Options{}
                                                       .withSampleRate (sr > 0.0 ? sr : 48000.0)
                                                       .withNumChannels (juce::jmax (1, buf.getNumChannels()))
                                                       .withBitsPerSample (24)))
            return writer->writeFromAudioSampleBuffer (buf, 0, buf.getNumSamples());
        return false;
    }
}

//==============================================================================
OrbitCabAudioProcessor::OrbitCabAudioProcessor()
    : AudioProcessor (BusesProperties()
                          .withInput  ("Input",  juce::AudioChannelSet::stereo(), true)
                          .withOutput ("Output", juce::AudioChannelSet::stereo(), true)),
      apvts (*this, nullptr, "PARAMS", orbitcab::createParameterLayout()),
      updateCheckerInstance (JucePlugin_VersionString, appPreferencesInstance)
{
    formatManager.registerBasicFormats();   // WAV/AIFF/FLAC… for IR decode (bundled + user files)

    // Stamp the saved state with a version from day one (CLAUDE.md non-negotiable);
    // the migration logic that reads it back comes later.
    apvts.state.setProperty ("stateVersion", 1, nullptr);

    // HEAD trim default: on. A global, on-by-default session setting kept as a state-tree
    // property (not a host param) so it rides save/load + snapshots + undo. See setHeadTrim.
    apvts.state.setProperty ("headTrim", true, nullptr);

    inputGainParam = apvts.getRawParameterValue ("inputGain");
    bypassParam    = apvts.getRawParameterValue ("bypass");
    mixABParam     = apvts.getRawParameterValue ("mixAB");
    gainParam      = apvts.getRawParameterValue ("gain");
    autoLevelParam = apvts.getRawParameterValue ("autoLevel");
    for (int i = 0; i < 2; ++i)
    {
        const juce::String s = (i == 0 ? "A" : "B");
        hpfOnP[i]   = apvts.getRawParameterValue ("hpfOn"   + s);
        hpfFreqP[i] = apvts.getRawParameterValue ("hpfFreq" + s);
        lpfOnP[i]   = apvts.getRawParameterValue ("lpfOn"   + s);
        lpfFreqP[i] = apvts.getRawParameterValue ("lpfFreq" + s);
        phaseP[i]   = apvts.getRawParameterValue ("phase"   + s);
        mixP[i]     = apvts.getRawParameterValue ("mix"     + s);
        trimOnP[i]  = apvts.getRawParameterValue ("trimOn"  + s);
        muteP[i]    = apvts.getRawParameterValue ("mute"    + s);
    }

    // Re-trim when TRIM-enable toggles (deferred to the message thread — it changes the
    // loaded IR, and the toggle can arrive on the audio thread). HEAD trim isn't a param;
    // setHeadTrim flags the reload directly (message thread → no listener needed).
    apvts.addParameterListener ("trimOnA", this);
    apvts.addParameterListener ("trimOnB", this);

    // Preset-centric first start: the live state IS a preset, and that preset is the factory
    // "Default" (bundled IR #16 + HPF) — not an ad-hoc bootstrap. Establishing it here (decode
    // + store the original IR) mirrors the supported setStateInformation-before-prepareToPlay
    // path; prepareToPlay re-applies it onto the prepared engine. A host that restores a
    // session right after construction simply overwrites this in setStateInformation.
    applyFactoryDefault();

    // Poll the reload flags on the message thread. The processor is constructed (and
    // destroyed) on the message thread, so start/stop the Timer here + in the destructor —
    // never from the audio or prepare/release path, whose thread is host-defined.
    startTimerHz (30);
}

OrbitCabAudioProcessor::~OrbitCabAudioProcessor()
{
    stopTimer();   // no poll callback may run while *this is being torn down
    apvts.removeParameterListener ("trimOnA", this);
    apvts.removeParameterListener ("trimOnB", this);
}

void OrbitCabAudioProcessor::parameterChanged (const juce::String& id, float)
{
    // This can run on the audio thread (host automation of the toggle), so do the absolute
    // minimum: flag the slot dirty. The 30 Hz timer below does the heavy rebuild off the
    // audio thread. An atomic store is the only hard-RT-safe primitive used on this path.
    if      (id == "trimOnA") pendingTrimReloadA.store (true, std::memory_order_relaxed);
    else if (id == "trimOnB") pendingTrimReloadB.store (true, std::memory_order_relaxed);
}

void OrbitCabAudioProcessor::timerCallback()
{
    // Message thread. Coalesces rapid toggles/drags (many flag stores between ticks → one
    // reload). Gated on enginePrepared so a flag set before prepareToPlay / after
    // releaseResources never rebuilds onto an engine with no convolvers.
    if (! enginePrepared.load (std::memory_order_acquire))
        return;
    if (pendingTrimReloadA.exchange (false)) applyTrimAndLoad (true);
    if (pendingTrimReloadB.exchange (false)) applyTrimAndLoad (false);
}

//==============================================================================
void OrbitCabAudioProcessor::prepareToPlay (double sampleRate, int maximumExpectedSamplesPerBlock)
{
    currentSampleRate = sampleRate;

    // Hand the stream to the headless core: it allocates filters/convolvers/scratch and
    // seeds its smoothers from the current parameter values (so a restored session
    // doesn't ramp from zero). The one place allocation is allowed — not the audio thread.
    engine.prepare (sampleRate, maximumExpectedSamplesPerBlock, getTotalNumOutputChannels(), packParams());

    // Re-apply the current IRs to the freshly-prepared convolvers (engine.prepare reset the
    // slots' reload-coalescing). setStateInformation may run before OR after
    // prepareToPlay, so only load the bundled default when no IR has been set yet; otherwise
    // re-apply what's already there (a restored session) instead of clobbering it.
    for (int i = 0; i < 2; ++i)
    {
        if (! slotState[(size_t) i].occupied())
            continue;                          // empty slot → leave the engine slot dry
        if (engine.slotHasOriginal (i))
            applyTrimAndLoad (i == 0);         // original survived the re-prepare → just re-trim
        else
            resolveSlot (i, slotState[(size_t) i]);   // original gone → reload from the identity
    }

    // Seed the auto-leveler from the loaded IR's energy so the makeup starts ~converged —
    // removes most of the startup kick at the root (#48); the soft-start below is now just
    // a short safety net for the convolver warm-up residue.
    engine.seedAutoLevel();

    enginePrepared.store (true, std::memory_order_release);   // arm the reload poll timer

    // One-shot startup fade (#48): a short ramp from silence on the first non-silent block,
    // covering the convolver warm-up the auto-level seed can't (the IR loads async). With the
    // seed doing the heavy lifting this is now ~imperceptible (was 150 ms before the seed).
    softStartArmed = true;
    softStart      = 1.0f;
    softStartStep  = (float) (1.0 / (0.03 * sampleRate));     // 30 ms
}

bool OrbitCabAudioProcessor::decodeReaderIntoEngine (std::unique_ptr<juce::AudioFormatReader> reader, int slotIdx)
{
    // Decode an IR into the slot's core cab::IRSlot (which keeps the original so TRIM can
    // re-truncate without re-decoding). This does NOT touch the slot's identity (ref / name /
    // status) or trim — the caller owns that (load = set identity here; resolve = from a
    // stored SlotIR). Loaded AS-IS (Normalise::no): the live wet->dry match does the leveling.
    if (reader == nullptr || reader->lengthInSamples <= 0)
        return false;                                 // unreadable / empty — caller leaves the slot untouched

    const double srLoaded = reader->sampleRate > 0.0 ? reader->sampleRate : currentSampleRate;

    // Cap the load (the "don't load big files" guard): only the first kMaxIRSeconds are
    // decoded, so a long file can't blow up the convolution or the embedded size.
    const juce::int64 maxSamples = (juce::int64) (kMaxIRSeconds * srLoaded);
    const int n = (int) juce::jmin (reader->lengthInSamples, maxSamples);

    juce::AudioBuffer<float> decoded ((int) reader->numChannels, n);
    reader->read (&decoded, 0, n, 0, true, true);

    // The IRSlot stores the original + detects leading silence (HEAD trim) on its own.
    engine.setSlotOriginalIR (slotIdx, decoded.getArrayOfReadPointers(),
                              decoded.getNumChannels(), n, srLoaded);
    return true;
}

//==============================================================================
juce::MemoryBlock OrbitCabAudioProcessor::canonicalWavForSlot (int slotIdx) const
{
    // The canonical, content-addressable form of a loaded external IR: its decoded original
    // re-encoded to a 24-bit WAV at the file's ORIGINAL sample rate (NOT the session rate),
    // capped at kMaxIRSeconds. This is the exact blob we embed, so computeBlobId(it) == the
    // IRPool key — session and portable preset share one id, and it's session-rate-independent.
    juce::MemoryBlock mb;
    encodeBufferToWav (engine.slotOriginal (slotIdx), engine.slotOriginalSampleRate (slotIdx), mb);
    return mb;
}

juce::String OrbitCabAudioProcessor::computeBlobId (const juce::MemoryBlock& canonicalWav)
{
    // "ir-" + hex(hash(base64(wav))). Matches the pre-v4 makePortable() hash exactly, so a
    // v3 portable preset's "ir-<hex>" ref re-derives to the SAME id on migration (seamless).
    const auto b64 = juce::Base64::toBase64 (canonicalWav.getData(), canonicalWav.getSize());
    return "ir-" + juce::String::toHexString (b64.hashCode64());
}

void OrbitCabAudioProcessor::setTrim (float fraction01, bool slotA)
{
    // Store the latest fraction + flag the slot dirty; the 30 Hz poll timer coalesces rapid
    // drags into one reload (calling the loader on every micro-move floods it so the final
    // position never lands). Called from the editor's waveform drag — message thread.
    slotState[slotA ? 0 : 1].trim = juce::jlimit (0.0f, 1.0f, fraction01);
    (slotA ? pendingTrimReloadA : pendingTrimReloadB).store (true, std::memory_order_relaxed);
}

void OrbitCabAudioProcessor::applyTrimAndLoad (bool slotA)
{
    // Rebuild + atomic-swap the (head-trimmed, then trimmed, faded) IR in the slot's core
    // cab::IRSlot, off the audio thread. TRIM/HEAD enables come from the params; the
    // drag fraction is the persisted position. Then refresh the host tail = longest slot.
    const int slotIdx = slotA ? 0 : 1;
    const bool trimOn = trimOnP[slotIdx] != nullptr && trimOnP[slotIdx]->load() > 0.5f;
    const bool headOn = getHeadTrim();                 // global, on-by-default session setting
    const float frac  = slotState[(size_t) slotIdx].trim;

    engine.slotApplyTrim (slotIdx, trimOn, frac, headOn);

    // Length comes from the message-thread slot status (NOT the audio mirror), so this is
    // correct even when called before the mirror is opened (see resolveSlot's ordering).
    using Status = orbitcab::state::SlotIR::Status;
    const double aSec = (slotState[0].status == Status::ready) ? engine.slotTrimmedSeconds (0) : 0.0;
    const double bSec = (slotState[1].status == Status::ready) ? engine.slotTrimmedSeconds (1) : 0.0;
    irLengthSeconds = juce::jmax (0.01, juce::jmax (aSec, bSec));
}

void OrbitCabAudioProcessor::setHeadTrim (bool on)
{
    // Message thread (gear settings toggle). Persist the flag on the state tree, then flag
    // BOTH slots for rebuild — the 30 Hz reload poll re-trims them off the audio thread
    // (same path as TRIM/IR-swap), gated by enginePrepared. RT rule: no reload happens here.
    apvts.state.setProperty ("headTrim", on, nullptr);
    pendingTrimReloadA.store (true, std::memory_order_relaxed);
    pendingTrimReloadB.store (true, std::memory_order_relaxed);
}

void OrbitCabAudioProcessor::loadBundledIR()
{
    if (auto* r = formatManager.createReaderFor (std::make_unique<juce::MemoryInputStream> (
            BinaryData::_01cookiemonster_wav, (size_t) BinaryData::_01cookiemonster_wavSize, false)))
    {
        if (decodeReaderIntoEngine (std::unique_ptr<juce::AudioFormatReader> (r), 0))
        {
            slotState[0] = orbitcab::state::SlotIR::makeBundled ("01-cookie-monster.wav");
            applyTrimAndLoad (true);
            setSlotAudioMirror (0);                    // open the gate only after the IR is swapped in
            bumpSound();
            return;
        }
    }

    // Fallback: byte-array load with JUCE's own normalisation (via the slot's convolver).
    // No decoded original here (so TRIM is a no-op), but keep the slot identity consistent.
    engine.slotLoadBytesFallback (0, BinaryData::_01cookiemonster_wav, (size_t) BinaryData::_01cookiemonster_wavSize);
    slotState[0] = orbitcab::state::SlotIR::makeBundled ("01-cookie-monster.wav");
    setSlotAudioMirror (0);
    bumpSound();
}

void OrbitCabAudioProcessor::loadIRFromFile (const juce::File& file, bool slotA)
{
    const int slotIdx = slotA ? 0 : 1;
    std::unique_ptr<juce::AudioFormatReader> reader (formatManager.createReaderFor (file));
    if (reader == nullptr)
        return;                                       // unreadable / missing → leave the slot as-is
    if (! decodeReaderIntoEngine (std::move (reader), slotIdx))
        return;                                       // decode failed → leave the slot as-is

    // Content-address the IR at load time: id = hash of the canonical embedded WAV. The same
    // id is used by the session AND a portable preset (no path→hash rewrite on export), and
    // the bytes are pooled so the IR survives a moved file / another machine.
    juce::MemoryBlock mb = canonicalWavForSlot (slotIdx);
    const auto blobId = computeBlobId (mb);
    embeddedIRs[blobId] = std::move (mb);

    slotState[(size_t) slotIdx] = orbitcab::state::SlotIR::makeExternal (blobId, file.getFileName(), file.getFullPathName());
    applyTrimAndLoad (slotA);                          // fresh IR → trim is 1.0 (makeExternal default)
    setSlotAudioMirror (slotIdx);                      // open the gate only after the IR is swapped in
    bumpSound();
}

void OrbitCabAudioProcessor::resolveSlot (int slotIdx, orbitcab::state::SlotIR target)
{
    // Load a slot from a stored identity (session / snapshot / undo / preset recall). The ONE
    // place a SlotIR becomes audio. Resolve order for external IRs: pooled bytes (by content
    // id) → the recovery localPath (decode + adopt) → else mark MISSING and clear the engine
    // slot (never leave the previous IR live under the restored identity — old bug F).
    using Status = orbitcab::state::SlotIR::Status;

    if (! target.occupied())
    {
        engine.clearSlotOriginal (slotIdx);
        slotState[(size_t) slotIdx] = orbitcab::state::SlotIR::makeEmpty();
        setSlotAudioMirror (slotIdx);
        return;
    }

    bool loaded = false;
    if (target.bundled)
    {
        for (const auto& b : orbitcab::bundledIRs())
            if (b.name == target.ref)
            {
                loaded = decodeReaderIntoEngine (std::unique_ptr<juce::AudioFormatReader> (
                    formatManager.createReaderFor (std::make_unique<juce::MemoryInputStream> (b.data, (size_t) b.size, false))), slotIdx);
                break;
            }
    }
    else
    {
        // 1) this session's pool, keyed by the content id.
        if (auto it = embeddedIRs.find (target.ref); it != embeddedIRs.end() && it->second.getSize() > 0)
            loaded = decodeReaderIntoEngine (std::unique_ptr<juce::AudioFormatReader> (formatManager.createReaderFor (
                std::make_unique<juce::MemoryInputStream> (it->second.getData(), it->second.getSize(), false))), slotIdx);

        // 2) fall back to the original file on disk; re-pool its (recomputed) bytes so the id is current.
        if (! loaded && target.localPath.isNotEmpty())
        {
            const juce::File f (target.localPath);
            if (f.existsAsFile())
                if (auto* r = formatManager.createReaderFor (f))
                    if (decodeReaderIntoEngine (std::unique_ptr<juce::AudioFormatReader> (r), slotIdx))
                    {
                        loaded = true;
                        juce::MemoryBlock mb = canonicalWavForSlot (slotIdx);
                        target.ref = computeBlobId (mb);          // re-key to the (possibly changed) content
                        embeddedIRs[target.ref] = std::move (mb);
                    }
        }
    }

    target.status = loaded ? Status::ready : Status::missing;
    if (! loaded)
        engine.clearSlotOriginal (slotIdx);           // missing → no fantom IR; UI shows "⚠ <name>"
    slotState[(size_t) slotIdx] = target;             // keep ref/name/localPath even when missing (for relink + UI)
    if (loaded)
        applyTrimAndLoad (slotIdx == 0);              // build + atomic-swap the trimmed IR FIRST…
    setSlotAudioMirror (slotIdx);                     // …THEN open the audio-thread gate (IR is ready)
}

void OrbitCabAudioProcessor::addUserIR (const juce::File& file)
{
    const auto path = file.getFullPathName();
    if (path.isEmpty())
        return;
    userIRPaths.removeString (path);                 // dedup → move to front (most recent)
    userIRPaths.insert (0, path);
    while (userIRPaths.size() > kMaxUserIRs)
        userIRPaths.remove (userIRPaths.size() - 1);
    userIRRev.fetch_add (1, std::memory_order_relaxed);   // editor re-syncs both slots' lists
}

void OrbitCabAudioProcessor::loadIRFromMemory (const void* data, size_t sizeInBytes, bool slotA,
                                           const juce::String& bundledName)
{
    // Bundled IR: wrap the embedded bytes in a stream and decode into the engine.
    // `false` => the stream does not own/copy the data (it's a static BinaryData blob).
    const int slotIdx = slotA ? 0 : 1;
    std::unique_ptr<juce::AudioFormatReader> reader (formatManager.createReaderFor (
        std::make_unique<juce::MemoryInputStream> (data, sizeInBytes, false)));
    if (! decodeReaderIntoEngine (std::move (reader), slotIdx))
        return;                                       // bad bytes → don't claim the slot loaded
    slotState[(size_t) slotIdx] = orbitcab::state::SlotIR::makeBundled (bundledName);
    applyTrimAndLoad (slotA);
    setSlotAudioMirror (slotIdx);                      // open the gate only after the IR is swapped in
    bumpSound();
}

void OrbitCabAudioProcessor::loadBundledByName (const juce::String& filename, bool slotA)
{
    // Find a bundled IR by its original filename and load it into the slot,
    // via the shared IRLibrary enumeration (one source of truth).
    for (const auto& b : orbitcab::bundledIRs())
        if (b.name == filename)
        {
            loadIRFromMemory (b.data, (size_t) b.size, slotA, filename);
            return;
        }
}

void OrbitCabAudioProcessor::clearSlotB()
{
    // Empty B (no cab): process feeds the dry signal through B (skipped when !ready). Mirrors
    // clearSlotA exactly — canonical empty so no stale ref/name/trim rides the state (bug G).
    engine.clearSlotOriginal (1);
    slotState[1] = orbitcab::state::SlotIR::makeEmpty();
    setSlotAudioMirror (1);
    bumpSound();
}

void OrbitCabAudioProcessor::clearSlotA()
{
    // Empty A (no cab): process feeds the dry signal through A — a clean passthrough, not
    // silence. A and B may both be empty → fully dry. Symmetric with clearSlotB.
    engine.clearSlotOriginal (0);
    slotState[0] = orbitcab::state::SlotIR::makeEmpty();
    setSlotAudioMirror (0);
    bumpSound();
}

//==============================================================================
// The v4 state pipeline — ONE capture/apply for live + workspace, used by sessions,
// A/B/C/D, undo/redo and presets. See StateModel.h for the data model.
//==============================================================================
orbitcab::state::SoundState OrbitCabAudioProcessor::captureLive()
{
    orbitcab::state::SoundState s;
    s.params   = apvts.copyState();            // includes the headTrim state property
    s.slots[0] = slotState[0];
    s.slots[1] = slotState[1];
    return s;
}

void OrbitCabAudioProcessor::applyLive (const orbitcab::state::SoundState& s)
{
    // Restore params FIRST (replaceState keeps the parameter objects, so cached raw-pointers
    // + editor attachments stay valid AND getHeadTrim() reads the restored value), then
    // resolve both slots from their stored identity. Callers bump the revisions.
    if (s.params.isValid())
        apvts.replaceState (s.params.createCopy());
    resolveSlot (0, s.slots[0]);
    resolveSlot (1, s.slots[1]);
}

orbitcab::state::Workspace OrbitCabAudioProcessor::currentWorkspace()
{
    orbitcab::state::Workspace w;
    w.live   = captureLive();
    w.active = activeSnapshot;
    for (int i = 0; i < kNumSnapshots; ++i)
        w.snapshots[(size_t) i] = snapshots[(size_t) i];
    w.snapshots[(size_t) activeSnapshot] = std::nullopt;   // the active register IS live — never stored twice
    return w;
}

void OrbitCabAudioProcessor::applyWorkspace (const orbitcab::state::Workspace& w)
{
    activeSnapshot = juce::jlimit (0, kNumSnapshots - 1, w.active);
    for (int i = 0; i < kNumSnapshots; ++i)
        snapshots[(size_t) i] = w.snapshots[(size_t) i];
    snapshots[(size_t) activeSnapshot] = std::nullopt;     // active is live, not a stored register
    applyLive (w.live);
    bumpSound();
    bumpWorkspace();
}

void OrbitCabAudioProcessor::switchToSnapshot (int index)
{
    if (index < 0 || index >= kNumSnapshots || index == activeSnapshot)
        return;
    snapshots[(size_t) activeSnapshot] = captureLive();    // stash live into the register we're leaving
    if (snapshots[(size_t) index].has_value())
        applyLive (*snapshots[(size_t) index]);            // recall an existing register
    // else: a fresh register inherits the current live sound (nothing to apply)
    activeSnapshot = index;
    snapshots[(size_t) activeSnapshot] = std::nullopt;     // active is live now
    bumpSound();
    bumpWorkspace();
}

//==============================================================================
// Undo / redo — coalesced full-WORKSPACE snapshots, so an A/B/C/D switch is exactly
// reversible (it restores the live sound, the active register AND the register contents).
//==============================================================================
void OrbitCabAudioProcessor::undoTick()
{
    // Driven by the editor timer. Commit one undo step once the state has settled
    // (unchanged for kUndoSettleTicks), so a slider drag becomes a single step.
    auto cur = orbitcab::state::toTree (currentWorkspace(), false);
    if (! undoBaseline.isValid())                       // first tick → seed the baseline
    {
        undoBaseline = cur;
        undoPrev     = cur;
        undoSettle   = 0;
        return;
    }
    if (! cur.isEquivalentTo (undoPrev))                // still changing → wait
    {
        undoPrev   = cur;
        undoSettle = 0;
        return;
    }
    if (! cur.isEquivalentTo (undoBaseline) && ++undoSettle >= kUndoSettleTicks)
    {
        undoStack.push_back (undoBaseline);
        if ((int) undoStack.size() > kMaxUndo)
            undoStack.erase (undoStack.begin());
        redoStack.clear();
        undoBaseline = cur;
        undoSettle   = 0;
    }
}

bool OrbitCabAudioProcessor::undo()
{
    if (undoStack.empty())
        return false;
    redoStack.push_back (orbitcab::state::toTree (currentWorkspace(), false));
    const auto target = undoStack.back();
    undoStack.pop_back();
    applyWorkspace (orbitcab::state::workspaceFromTree (target));
    // Re-seed from the ACTUAL post-apply workspace (resolveSlot may re-key an external ref
    // path→content-id), so the next undoTick doesn't record a phantom step.
    undoBaseline = undoPrev = orbitcab::state::toTree (currentWorkspace(), false);
    undoSettle   = 0;
    return true;
}

bool OrbitCabAudioProcessor::redo()
{
    if (redoStack.empty())
        return false;
    undoStack.push_back (orbitcab::state::toTree (currentWorkspace(), false));
    const auto target = redoStack.back();
    redoStack.pop_back();
    applyWorkspace (orbitcab::state::workspaceFromTree (target));
    // Re-seed from the ACTUAL post-apply workspace (resolveSlot may re-key an external ref
    // path→content-id), so the next undoTick doesn't record a phantom step.
    undoBaseline = undoPrev = orbitcab::state::toTree (currentWorkspace(), false);
    undoSettle   = 0;
    return true;
}

const juce::MemoryBlock* OrbitCabAudioProcessor::embeddedIRBytes (const juce::String& path) const
{
    auto it = embeddedIRs.find (path);
    return (it != embeddedIRs.end() && it->second.getSize() > 0) ? &it->second : nullptr;
}

void OrbitCabAudioProcessor::releaseResources()
{
    // Disarm the reload poll timer before tearing down DSP state, so timerCallback can't
    // rebuild onto a reset engine. Then drop the engine's transient state (filter/convolver/
    // follower); prepareToPlay re-seeds everything + re-applies the IRs before audio resumes.
    enginePrepared.store (false, std::memory_order_release);
    engine.reset();
    softStartArmed = true;          // re-arm the startup fade for the next play (#48)
    softStart      = 1.0f;
}

bool OrbitCabAudioProcessor::isBusesLayoutSupported (const BusesLayout& layouts) const
{
    // Accept matching mono->mono or stereo->stereo only; reject the rest.
    const auto& mainOut = layouts.getMainOutputChannelSet();
    const auto& mainIn  = layouts.getMainInputChannelSet();

    if (mainOut != juce::AudioChannelSet::mono()
        && mainOut != juce::AudioChannelSet::stereo())
        return false;

    return mainIn == mainOut;
}

//==============================================================================
void OrbitCabAudioProcessor::processBlock (juce::AudioBuffer<float>& buffer,
                                       juce::MidiBuffer& midiMessages)
{
    juce::ignoreUnused (midiMessages);
    juce::ScopedNoDenormals noDenormals;

    const int numCh      = getTotalNumInputChannels();
    const int numSamples = buffer.getNumSamples();

    // Clear any output channels without a matching input (avoids garbage).
    for (int ch = numCh; ch < getTotalNumOutputChannels(); ++ch)
        buffer.clear (ch, 0, numSamples);

    // The whole signal path lives in the headless core (cab::CabEngine). Pack the
    // current parameters (RT-safe atomic loads) and hand it the planar channels in
    // place; `isNonRealtime()` lets it skip the spectrum capture during a bounce.
    engine.process (buffer.getArrayOfWritePointers(), numCh, numSamples, packParams(), isNonRealtime());

    // One-shot soft-start: fade the output up from silence on the first non-silent block
    // after prepareToPlay / releaseResources, to mask the engine's auto-level + convolver
    // warm-up transient (#48). A host-side cosmetic — kept out of the pure DSP core.
    if (softStartArmed && buffer.getMagnitude (0, numSamples) > 1.0e-5f)
    {
        softStartArmed = false;
        softStart      = 0.0f;
    }
    if (softStart < 1.0f)
    {
        const int chs = buffer.getNumChannels();
        for (int n = 0; n < numSamples; ++n)
        {
            const float ss = softStart;
            for (int ch = 0; ch < chs; ++ch)
                buffer.getWritePointer (ch)[n] *= ss;
            softStart = juce::jmin (1.0f, softStart + softStartStep);
        }
    }
}

//==============================================================================
// Pack the cached APVTS atomics into a plain cab::Params for the core. RT-safe
// (only atomic loads); called from processBlock and to seed the engine in prepare.
cab::Params OrbitCabAudioProcessor::packParams() const
{
    cab::Params p;
    p.inputGainDb  = inputGainParam->load();
    p.outputGainDb = gainParam->load();
    p.mixAB01      = mixABParam->load() * 0.01f;
    p.bypass       = bypassParam->load()    > 0.5f;
    p.autoLevel    = autoLevelParam->load() > 0.5f;
    p.aLoaded      = slotAudioLoaded[0].load (std::memory_order_relaxed);
    p.bLoaded      = slotAudioLoaded[1].load (std::memory_order_relaxed);
    for (int i = 0; i < 2; ++i)
    {
        p.slot[i].hpfOn    = hpfOnP[i]->load() > 0.5f;
        p.slot[i].lpfOn    = lpfOnP[i]->load() > 0.5f;
        p.slot[i].phase    = phaseP[i]->load() > 0.5f;
        p.slot[i].mute     = muteP[i]->load()  > 0.5f;
        p.slot[i].hpfHz    = hpfFreqP[i]->load();
        p.slot[i].lpfHz    = lpfFreqP[i]->load();
        p.slot[i].dryWet01 = mixP[i]->load() * 0.01f;
    }
    return p;
}

//==============================================================================
juce::AudioProcessorEditor* OrbitCabAudioProcessor::createEditor()
{
    return new OrbitCabAudioProcessorEditor (*this);
}

//==============================================================================
std::vector<orbitcab::IrRef> OrbitCabAudioProcessor::currentIrRefs() const
{
    // Display-layer references for the preset <meta>: which IR each slot uses, so a browser
    // can show them without decoding audio or applying state. The functional load still goes
    // through <Workspace>/<IRPool>. With v4's content-addressed identity the descriptive `id`
    // is the external content id (no longer dormant); `fallback` is path-free by construction.
    auto make = [] (const orbitcab::state::SlotIR& s, const char* slot)
    {
        orbitcab::IrRef r;
        r.slot     = slot;
        r.bundled  = s.bundled;
        r.name     = s.displayName.upToLastOccurrenceOf (".", false, false);   // drop extension for display
        r.id       = s.bundled ? juce::String() : s.ref;       // external: the content id
        r.fallback = s.bundled ? s.ref : s.displayName;        // bundled filename; external: bare name (no path)
        return r;
    };

    std::vector<orbitcab::IrRef> refs;
    if (slotState[0].occupied()) refs.push_back (make (slotState[0], "A"));
    if (slotState[1].occupied()) refs.push_back (make (slotState[1], "B"));
    return refs;
}

//==============================================================================
// Preset-centric model: the factory Default + dirty tracking.
//==============================================================================
void OrbitCabAudioProcessor::loadFactoryDefaultIR()
{
    // The factory Default's cabinet: bundled Emerald IR #16. By filename PREFIX (not a
    // hardcoded full name) so a later rename of the bundled tree doesn't silently fall
    // through to the cookie-monster fallback.
    for (const auto& b : orbitcab::bundledIRs())
        if (b.name.startsWith ("16"))
        {
            loadIRFromMemory (b.data, (size_t) b.size, true, b.name);
            return;
        }
    loadBundledIR();   // fallback (shouldn't happen): the original bootstrap IR
}

void OrbitCabAudioProcessor::applyFactoryDefault()
{
    // The factory starting point (preset-centric first start + the editor's "Default" item):
    // a clean single-box sound — bundled IR #16 with the HPF engaged. Reset every parameter
    // to its default first so the result is reproducible regardless of the current state,
    // then load the IR + arm the HPF + stamp the read-only "Default" identity. Message-thread.
    for (auto* p : getParameters())
        if (auto* rp = dynamic_cast<juce::RangedAudioParameter*> (p))
            rp->setValueNotifyingHost (rp->getDefaultValue());

    clearSlotB();                                   // box II empty (single IR; clear canonicalises its trim)
    loadFactoryDefaultIR();                          // box I → IR #16 (resets slot A trim to full)
    if (auto* q = apvts.getParameter ("hpfOnA"))
        q->setValueNotifyingHost (1.0f);             // HPF on (default 80 Hz)
    setHeadTrim (true);                              // factory HEAD-trim on (a state property, not a param)

    // A fresh Default is a clean starting point: clear the A/B/C/D compare registers and the
    // undo history so neither resurrects the previous preset (bug B / the dop#4 contradiction).
    activeSnapshot = 0;
    for (auto& snap : snapshots) snap = std::nullopt;
    undoStack.clear();  redoStack.clear();
    undoBaseline = juce::ValueTree();  undoPrev = juce::ValueTree();  undoSettle = 0;
    bumpWorkspace();

    currentMeta      = orbitcab::PresetMeta();
    currentMeta.name = "Default";
    presetIsFactory  = true;
    captureBaseline();                               // a fresh Default is clean (not dirty)
}

void OrbitCabAudioProcessor::markPresetModified()
{
    if (currentMeta.createdAt.isEmpty())
        currentMeta.createdAt = orbitcab::nowIso8601();
    currentMeta.modifiedAt = orbitcab::nowIso8601();
}

juce::String OrbitCabAudioProcessor::stateFingerprint()
{
    // Cheap, stable hash of the preset-defining live sound (params incl. headTrim + each slot's
    // identity/trim). Excludes <meta>, view-prefs, snapshots, undo AND localPath, so only
    // sound-affecting edits flip it and the same sound hashes identically across machines.
    return orbitcab::state::fingerprint (captureLive());
}

//==============================================================================
juce::ValueTree OrbitCabAudioProcessor::buildStateTree (bool forPreset)
{
    // Wrap the parameter tree + per-slot IR references in one root so a saved
    // DAW session (or a preset) restores both the params and which IRs were loaded. Each
    // slot stores a *reference* (bundled filename or file path) + trim. External (user)
    // IRs additionally embed their audio in an IRPool node so the session/preset is
    // self-contained — survives a moved file / another machine. Bundled IRs are
    // never embedded (their bytes live in the plugin binary).
    juce::ValueTree root ("OrbitCabState");
    root.setProperty ("stateVersion", orbitcab::state::kStateVersion, nullptr);   // 4 = single-source-of-truth <Workspace>/<Slot> model

    // Preset identity (preset-centric model): the descriptive metadata + which IRs the live
    // state uses, as JSON in a <meta> child. Built into a LOCAL copy so serialising never
    // mutates the live member (some hosts call getStateInformation off the message thread),
    // and stamped with the build version + a modified timestamp. The functional load stays
    // in <IR>/<IRPool>; this is the cheap descriptive layer a browser reads on its own.
    {
        orbitcab::PresetMeta meta = currentMeta;
        // Refresh the descriptive IR refs from the live slots, but carry over any unknown
        // per-IR fields (extra) the loaded preset had for the same slot — forward-compat.
        auto fresh = currentIrRefs();
        for (auto& r : fresh)
            for (const auto& old : currentMeta.irRefs)
                if (old.slot == r.slot) { r.extra = old.extra; break; }
        meta.irRefs     = std::move (fresh);
        meta.appVersion = JucePlugin_VersionString;
        // modifiedAt is stamped only on an explicit Save (markPresetModified), never here —
        // serialisation must be deterministic so a host doesn't see "changed" state on poll.
        juce::ValueTree metaTree ("meta");
        metaTree.setProperty ("json", orbitcab::toJSON (meta.toVar()), nullptr);
        if (! forPreset)
        {
            // Session bookkeeping (NOT shareable): the dirty baseline + factory flag, so a
            // dirty "Default *" and "this is the read-only Default" survive a DAW reload.
            metaTree.setProperty ("baselineHash", presetBaselineFingerprint, nullptr);
            metaTree.setProperty ("factory",      presetIsFactory,           nullptr);
        }
        else
        {
            metaTree.setProperty ("factory", false, nullptr);   // a shared/exported preset is never the Default
        }
        root.appendChild (metaTree, nullptr);
    }

    // The sound. A SESSION carries the whole compare workspace (live + the 4 registers) + the
    // recents list; a PORTABLE PRESET carries only the live sound (no registers, no paths,
    // no recents). Both go through the single v4 (de)serialiser so they can't drift.
    if (forPreset)
    {
        root.appendChild (orbitcab::state::toTree (captureLive(), /*portable*/ true), nullptr);
    }
    else
    {
        root.appendChild (orbitcab::state::toTree (currentWorkspace(), /*portable*/ false), nullptr);
        root.setProperty ("userIRs", userIRPaths.joinIntoString ("\n"), nullptr);   // recents (session-only)
    }

    // IRPool: embed every external IR's audio referenced by the live sound (and, for a session,
    // by any register), keyed by content id, deduped. Bundled refs are never embedded.
    {
        juce::StringArray ids;
        auto addSlot = [&] (const orbitcab::state::SlotIR& s)
        { if (s.occupied() && ! s.bundled && s.ref.isNotEmpty()) ids.addIfNotAlreadyThere (s.ref); };

        addSlot (slotState[0]);
        addSlot (slotState[1]);
        if (! forPreset)
            for (int i = 0; i < kNumSnapshots; ++i)
                if (snapshots[(size_t) i].has_value())
                {
                    addSlot (snapshots[(size_t) i]->slots[0]);
                    addSlot (snapshots[(size_t) i]->slots[1]);
                }

        juce::ValueTree pool ("IRPool");
        for (const auto& id : ids)
            if (auto it = embeddedIRs.find (id); it != embeddedIRs.end() && it->second.getSize() > 0)
            {
                juce::ValueTree e ("E");
                e.setProperty ("id",  id, nullptr);
                e.setProperty ("wav", juce::Base64::toBase64 (it->second.getData(), it->second.getSize()), nullptr);
                pool.appendChild (e, nullptr);
            }
        root.appendChild (pool, nullptr);
    }

    return root;
}

//==============================================================================
void OrbitCabAudioProcessor::getStateInformation (juce::MemoryBlock& destData)
{
    if (auto xml = buildStateTree().createXml())
        copyXmlToBinary (*xml, destData);
}

void OrbitCabAudioProcessor::getStateForPreset (juce::MemoryBlock& destData)
{
    // Portable export. forPreset=true builds the live sound in portable mode (no localPath, no
    // recents) and drops the A/B/C/D registers. With v4's content-addressed refs there are no
    // file paths to strip — the ref IS the path-free content id — so the old makePortable() and
    // its name-from-ref rewrite (which baked the hash in as the display name) are gone.
    auto root = buildStateTree (true);
    if (auto xml = root.createXml())
        copyXmlToBinary (*xml, destData);
}

void OrbitCabAudioProcessor::setStateInformation (const void* data, int sizeInBytes)
{
    auto xml = getXmlFromBinary (data, sizeInBytes);
    if (xml == nullptr)
        return;

    auto root = juce::ValueTree::fromXml (*xml);
    bool migratedLegacy = false;                    // true → re-baseline clean after the load

    if (root.hasType ("OrbitCabState"))
    {
        // <meta> identity + session bookkeeping. Absent → clean default (name derives from the file).
        if (auto m = root.getChildWithName ("meta"); m.isValid())
        {
            currentMeta = orbitcab::PresetMeta::fromVar (orbitcab::parseJSON (m.getProperty ("json").toString()));
            presetBaselineFingerprint = m.getProperty ("baselineHash", {}).toString();
            presetIsFactory = (bool) m.getProperty ("factory", false);
        }
        else
        {
            currentMeta = orbitcab::PresetMeta();
            presetBaselineFingerprint.clear();
            presetIsFactory = false;
        }

        // Recents (session-only; a portable preset carries none → cleared).
        userIRPaths.clear();
        if (root.hasProperty ("userIRs"))
        {
            userIRPaths.addLines (root.getProperty ("userIRs").toString());
            userIRPaths.removeEmptyStrings();
        }

        // Rehydrate the embedded-IR pool FRESH for the incoming state (never accumulate across
        // loads — the old bug where a later restore could pick up a previous preset's bytes).
        // v4 keys by content "id"; v3 keyed by "path" — accept both.
        embeddedIRs.clear();
        if (auto pool = root.getChildWithName ("IRPool"); pool.isValid())
            for (auto e : pool)
            {
                juce::String key = e.getProperty ("id", {}).toString();
                if (key.isEmpty()) key = e.getProperty ("path", {}).toString();   // v3 fallback
                const juce::String b64 = e.getProperty ("wav").toString();
                if (key.isEmpty() || b64.isEmpty())
                    continue;
                if ((size_t) b64.getNumBytesAsUTF8() / 4 * 3 > kMaxEmbeddedIRBytes)
                    continue;                          // oversized blob (crafted/corrupt) → skip, don't OOM
                juce::MemoryOutputStream mos;
                if (juce::Base64::convertFromBase64 (mos, b64) && mos.getDataSize() <= kMaxEmbeddedIRBytes)
                    embeddedIRs[key] = juce::MemoryBlock (mos.getData(), mos.getDataSize());
            }

        if (auto ws = root.getChildWithName ("Workspace"); ws.isValid())
        {
            applyWorkspace (orbitcab::state::workspaceFromTree (ws));   // v4 session
        }
        else if (auto sound = root.getChildWithName ("Sound"); sound.isValid())
        {
            orbitcab::state::Workspace w;                              // v4 portable preset (live only) →
            w.live = orbitcab::state::soundFromTree (sound);           // reset the compare registers (bug B)
            applyWorkspace (w);
        }
        else
        {
            // v3 → v4 migration: legacy <PARAMS> + flat <IR> (+ optional <Snapshots>). Re-key
            // external path/hash refs to the v4 content id using the rehydrated pool.
            auto params    = root.getChildWithName (apvts.state.getType());
            auto legacyIR  = root.getChildWithName ("IR");
            auto rekey = [this] (orbitcab::state::SoundState& s)
            {
                for (auto& slot : s.slots)
                {
                    if (! slot.occupied() || slot.bundled) continue;
                    const juce::String oldKey = slot.localPath.isNotEmpty() ? slot.localPath : slot.ref;
                    if (auto it = embeddedIRs.find (oldKey); it != embeddedIRs.end() && it->second.getSize() > 0)
                    {
                        const auto newId = computeBlobId (it->second);
                        if (newId != oldKey) embeddedIRs[newId] = it->second;   // copy under the content id
                        slot.ref = newId;
                    }
                    // else: leave ref; resolveSlot will try localPath on disk and re-pool it.
                }
            };

            orbitcab::state::Workspace w;
            w.live = orbitcab::state::migrateLegacySound (legacyIR, params);
            rekey (w.live);
            if (auto snaps = root.getChildWithName ("Snapshots"); snaps.isValid())
            {
                w.active = juce::jlimit (0, kNumSnapshots - 1, (int) snaps.getProperty ("active", 0));
                int i = 0;
                for (auto sNode : snaps)
                {
                    if (i >= kNumSnapshots) break;
                    if (auto snap = sNode.getChildWithName ("Snap"); snap.isValid())
                    {
                        auto ss = orbitcab::state::migrateLegacySound (snap.getChildWithName ("IR"),
                                                                       snap.getChildWithName (apvts.state.getType()));
                        rekey (ss);
                        w.snapshots[(size_t) i] = ss;
                    }
                    ++i;
                }
            }
            migratedLegacy = true;
            applyWorkspace (w);
        }
    }
    else if (xml->hasTagName (apvts.state.getType()))
    {
        // pre-v3: just the PARAMS tree (no IR info) → params only, both slots empty.
        currentMeta = orbitcab::PresetMeta();
        presetBaselineFingerprint.clear();
        presetIsFactory = false;
        embeddedIRs.clear();
        userIRPaths.clear();
        orbitcab::state::Workspace w;
        w.live.params = root.createCopy();
        migratedLegacy = true;
        applyWorkspace (w);
    }

    // Migration: HEAD trim was per-slot params (headOnA/B, default off) through 1.0.x; it's
    // now the global `headTrim` property (default on). A session saved before 1.1 carries no
    // such property — fall back to the OLD default (off) so opening an old project doesn't
    // silently start head-trimming the IRs. Post-1.1 sessions carry the property and keep
    // their value, so property-absence IS the version marker (no stateVersion bump needed).
    // The IR re-trim is deferred to the reload poll, which reads getHeadTrim() after this returns.
    if (! apvts.state.hasProperty ("headTrim"))
    {
        apvts.state.setProperty ("headTrim", false, nullptr);   // pre-1.1: HEAD was off by default
        // resolveSlot already trimmed with HEAD defaulting ON — re-trim both now it's known off.
        if (isSlotALoaded()) applyTrimAndLoad (true);
        if (isSlotBLoaded()) applyTrimAndLoad (false);
    }

    // A migrated v3 state stored its baseline hash in the OLD fingerprint format, which never
    // matches the v4 hash → it would load spuriously "dirty". Re-baseline to the settled v4
    // state so an unchanged old project opens clean.
    if (migratedLegacy)
        presetBaselineFingerprint = stateFingerprint();

    userIRRev.fetch_add (1, std::memory_order_relaxed);   // editor rebuilds the shared recents menus

    // A loaded session/preset is a fresh starting point — drop undo history and re-seed
    // the baseline (lazily, on the next undoTick) so you can't undo past the load.
    undoStack.clear();
    redoStack.clear();
    undoBaseline = juce::ValueTree();
    undoPrev     = juce::ValueTree();
    undoSettle   = 0;
}

//==============================================================================
// The factory the host calls to instantiate the plugin.
juce::AudioProcessor* JUCE_CALLTYPE createPluginFilter()
{
    return new OrbitCabAudioProcessor();
}
